### PR TITLE
support passing java opts, fix type defs, fixes #7

### LINKED ISSUE #7: Increasing Heap Size
I'm running out of memory running dynamoDB locally. I have been trying to increase the heap size on startup, like this:

DynamoDbLocal.launch(8000, null, ['-sharedDb','-Xms4096m','-Xmx8192m'])

But either I'm using a ridiculous amount of memory, or it's not working. Should the above work?

### PR DESCRIPTION
**Pull request by pickworth**

### CODE REVIEW

**Comment by pickworth** [comment]
```
await DynamoDbLocal.launch(
        8000, 
        null, 
        [], 
        true, 
        true,
        '-Xmx256m'
);
```

**Review by carera — APPROVED** [review]
LGTM

**Review by joshloh — APPROVED** [review]
lgtm

**Comment by rynop** [comment]
thx all. published on npm as `0.0.27`

**Pull request merged**
